In [32]:
import numpy as np
import xgboost as xgb
import pandas as pd
from sklearn import datasets

In [33]:
iris=datasets.load_iris()
#Even number's data is for training
trainX=iris.data[1::2,:]
trainY=iris.target[1::2]
#Odd number's data is for test
testX=iris.data[2::2,:]
testY=iris.target[2::2]

In [34]:
#transform to DMatrix
trainX=pd.DataFrame(trainX)
trainX.columns=iris.feature_names
dtrain=xgb.DMatrix(trainX.as_matrix(),label=trainY.tolist())
testX=pd.DataFrame(testX)
testX.columns=iris.feature_names
dtest=xgb.DMatrix(testX.as_matrix())

In [35]:
np.random.seed(131)

In [36]:
params={'objective':'multi:softprob',
       'eval_metric':'mlogloss',
       'eta':0.3, # default=0.3
       'max_depth':6, #max depth of tree [default=6]
       'min_child_weight':1, #[default=1]
       'subsample':1,#[default=1]
       'num_class':3
       }

In [37]:
#do training
bst=xgb.train(params,dtrain,num_boost_round=18)

In [38]:
# calc variable score
imp=bst.get_fscore()
print(imp)

{'f1': 4, 'f0': 3, 'f3': 39, 'f2': 70}


In [39]:
cv=xgb.cv(params,dtrain,num_boost_round=40,nfold=10)
cv.head(4)

/home/vagrant/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/xgboost/training.py:272: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  idset = [randidx[(i * kstep): min(len(randidx), (i + 1) * kstep)] for i in range(nfold)]


test-mlogloss-mean  test-mlogloss-std  train-mlogloss-mean  \
0            0.771650           0.038101             0.753921   
1            0.568656           0.053669             0.545685   
2            0.436034           0.068086             0.408324   
3            0.346780           0.086041             0.313613   

   train-mlogloss-std  
0            0.008132  
1            0.007138  
2            0.006829  
3            0.006850

In [40]:
bst=xgb.train(params,dtrain,18)
pred=bst.predict(dtest)
pred=pd.DataFrame(pred)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(testY, pred.idxmax(axis=1)))

[[24  0  0]
 [ 0 21  4]
 [ 0  1 24]]


/home/vagrant/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/xgboost/core.py:840: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  preds = preds.reshape(nrow, preds.size / nrow)
